using CRM.winforms;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace CRM.winforms.Controls
{
    /// <summary>
    /// Customer Retention page.
    ///
    /// Shows retention opportunities generated by the RetentionEngine from REAL
    /// customer history — loyalty rewards, discounts, follow-ups and
    /// re-engagement — each with the measurable basis on display:
    /// transaction count, total spending, days since last transaction, etc.
    /// Staff can act on any recommendation by logging an outreach contact.
    /// </summary>
    [DesignerCategory("Code")]
    public class RetentionControl : UserControl
    {
        // ═══════════ STATE ═══════════
        private readonly ApiClient _api = new ApiClient();
        private List<RetentionRecommendationDto> _all = new();

        private const string ColActions = "colActions";
        private ContextMenuStrip _actionsMenu = null!;
        private int _menuRowIndex = -1;
        private int _hoverRow = -1;
        private readonly ToolTip _tips = new ToolTip { InitialDelay = 500, ReshowDelay = 200 };

        // ═══════════ CONTROLS ═══════════
        private Label lblTitle = null!;
        private Label lblSubtitle = null!;
        private FlatButton btnRefresh = null!;
        private FlatButton btnLogOutreach = null!;

        private SurfaceCard card = null!;
        private Label lblGridTitle = null!;
        private Label lblCount = null!;
        private SearchBox search = null!;

        private Panel pnlTabs = null!;
        private readonly List<TabButton> _tabs = new();
        private string _category = "All";

        private DataGridView dgv = null!;
        private StateView state = null!;

        public RetentionControl()
        {
            SetStyle(ControlStyles.AllPaintingInWmPaint | ControlStyles.OptimizedDoubleBuffer
                   | ControlStyles.UserPaint | ControlStyles.ResizeRedraw, true);
            DoubleBuffered = true;
            BackColor = AppTheme.Background;
            AutoScaleMode = AutoScaleMode.Font;

            BuildActionsMenu();
            BuildUi();

            this.Load += async (s, e) => await ReloadAsync();
        }

        // ═══════════ UI ═══════════
        private void BuildUi()
        {
            lblTitle = new Label
            {
                Text = "Retention",
                Font = UiKit.T.Title,
                ForeColor = UiKit.T.Ink,
                AutoSize = true,
                BackColor = Color.Transparent
            };

            lblSubtitle = new Label
            {
                Text = "Opportunities computed from real customer history — every row shows WHY this customer was identified",
                Font = UiKit.T.Subtitle,
                ForeColor = UiKit.T.InkMuted,
                AutoSize = true,
                BackColor = Color.Transparent
            };

            btnRefresh = new FlatButton("Refresh", "\uE72C");
            btnRefresh.Click += async (s, e) => await ReloadAsync();
            _tips.SetToolTip(btnRefresh, "Recompute recommendations from the database");

            btnLogOutreach = new FlatButton("Log outreach", "\uE8BD");
            btnLogOutreach.Click += (s, e) => LogOutreachForSelected();
            _tips.SetToolTip(btnLogOutreach, "Log outreach for selected customer");

            Controls.Add(lblTitle);
            Controls.Add(lblSubtitle);
            Controls.Add(btnRefresh);
            Controls.Add(btnLogOutreach);

            // Category tabs
            pnlTabs = new Panel { BackColor = AppTheme.Background };

            foreach (var cat in new[] { "All", "Reward", "Discount", "Follow-up", "Re-engagement" })
            {
                var tab = new TabButton(cat, cat);
                tab.Click += (s, e) => SwitchCategory(cat);
                _tabs.Add(tab);
                pnlTabs.Controls.Add(tab);
            }

            _tabs[0].IsActive = true;
            Controls.Add(pnlTabs);

            card = new SurfaceCard();

            lblGridTitle = new Label
            {
                Text = "Retention opportunities",
                Font = UiKit.T.Section,
                ForeColor = UiKit.T.Ink,
                AutoSize = true,
                BackColor = Color.Transparent
            };

            lblCount = new Label
            {
                Text = "",
                Font = UiKit.T.Small,
                ForeColor = UiKit.T.InkFaint,
                AutoSize = true,
                BackColor = Color.Transparent
            };

            search = new SearchBox { PlaceholderText = "Search name, email, phone or basis" };
            search.Inner.TextChanged += (s, e) => ApplySearch();
            _tips.SetToolTip(search, "Search  (Ctrl+F)");

            dgv = new DataGridView();
            StyleGrid(dgv);
            dgv.CellPainting += Dgv_CellPainting;
            dgv.CellClick += Dgv_CellClick;
            dgv.CellDoubleClick += Dgv_CellDoubleClick;
            dgv.CellMouseEnter += Dgv_CellMouseEnter;
            dgv.CellMouseLeave += Dgv_CellMouseLeave;
            dgv.MouseLeave += (s, e) => { _hoverRow = -1; dgv.Invalidate(); };

            state = new StateView { Visible = false };

            card.Controls.Add(lblGridTitle);
            card.Controls.Add(lblCount);
            card.Controls.Add(search);
            card.Controls.Add(dgv);
            card.Controls.Add(state);

            Controls.Add(card);

            Resize += (s, e) => LayoutUi();
        }

        private void SwitchCategory(string category)
        {
            _category = category;
            foreach (var tab in _tabs)
                tab.IsActive = tab.Category == category;
            ApplySearch();
        }

        protected override void OnPaint(PaintEventArgs e)
        {
            base.OnPaint(e);
            UiKit.Quality(e.Graphics);

            int y = lblSubtitle.Bottom + UiKit.T.S4;
            using var pen = new Pen(UiKit.T.Line, 1);
            e.Graphics.DrawLine(pen, 0, y, Width, y);
        }

        private void LayoutUi()
        {
            if (Width <= 0 || Height <= 0) return;

            lblTitle.Location = new Point(0, 0);
            int subtitleY = lblTitle.PreferredHeight + UiKit.T.S1;
            lblSubtitle.Location = new Point(1, subtitleY);

            int rightX = Width;
            btnLogOutreach.Size = new Size(btnLogOutreach.PreferredWidth, UiKit.T.ButtonHeight);
            btnLogOutreach.Location = new Point(rightX - btnLogOutreach.Width, UiKit.T.S1);
            rightX -= btnLogOutreach.Width + 8;

            btnRefresh.Size = new Size(btnRefresh.PreferredWidth, UiKit.T.ButtonHeight);
            btnRefresh.Location = new Point(rightX - btnRefresh.Width, UiKit.T.S1);

            int dividerY = subtitleY + lblSubtitle.PreferredHeight + UiKit.T.S4;
            int tabsY = dividerY + UiKit.T.S5;

            int tabsX = 0;
            foreach (var tab in _tabs)
            {
                int w = tab.GetPreferredWidth();
                tab.Location = new Point(tabsX, 0);
                tab.Size = new Size(w, 34);
                tabsX += w + 4;
            }
            pnlTabs.Location = new Point(0, tabsY);
            pnlTabs.Size = new Size(tabsX, 34);

            int cardTop = tabsY + 34 + UiKit.T.S5;
            int cardHeight = Math.Max(240, Height - cardTop);

            card.Location = new Point(0, cardTop);
            card.Size = new Size(Width, cardHeight);

            const int cp = UiKit.T.S5;

            lblGridTitle.Location = new Point(cp, UiKit.T.S5 - 2);
            lblCount.Location = new Point(
                lblGridTitle.Right + UiKit.T.S2,
                lblGridTitle.Top + lblGridTitle.PreferredHeight - lblCount.PreferredHeight - 2);

            int toolbarY = lblGridTitle.Bottom + UiKit.T.S4;

            int searchW = Math.Min(320, Math.Max(200, card.Width - cp * 2));
            search.Size = new Size(searchW, UiKit.T.InputHeight);
            search.Location = new Point(card.Width - cp - searchW, toolbarY);

            int gridTop = toolbarY + UiKit.T.InputHeight + UiKit.T.S4;
            int gridW = card.Width - cp * 2;
            int gridH = card.Height - gridTop - cp;

            if (gridW > 100 && gridH > 60)
            {
                dgv.Location = new Point(cp, gridTop);
                dgv.Size = new Size(gridW, gridH);
                state.Location = new Point(cp, gridTop);
                state.Size = new Size(gridW, gridH);
            }
        }

        // ═══════════ DATA ═══════════
        public async Task ReloadAsync()
        {
            try
            {
                _all = await _api.GetRetentionRecommendationsAsync();
                ApplySearch();
            }
            catch (Exception ex)
            {
                _all = new List<RetentionRecommendationDto>();
                ApplySearch();

                MessageBox.Show(
                    $"Couldn't load retention recommendations.\n\n{ex.Message}",
                    "Connection problem",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
            }
        }

        private void ApplySearch()
        {
            var term = search.Inner.Text?.Trim() ?? string.Empty;

            IEnumerable<RetentionRecommendationDto> q = _all;

            if (_category != "All")
                q = q.Where(x => x.Category.Equals(_category, StringComparison.OrdinalIgnoreCase));

            if (!string.IsNullOrEmpty(term))
            {
                q = q.Where(x =>
                    (x.CustomerName ?? "").Contains(term, StringComparison.OrdinalIgnoreCase) ||
                    (x.Email ?? "").Contains(term, StringComparison.OrdinalIgnoreCase) ||
                    (x.Phone ?? "").Contains(term, StringComparison.OrdinalIgnoreCase) ||
                    (x.Basis ?? "").Contains(term, StringComparison.OrdinalIgnoreCase));
            }

            var view = q.ToList();

            dgv.DataSource = null;
            dgv.DataSource = view;
            ConfigureColumns();
            AddActionsColumn();

            lblCount.Text = view.Count == _all.Count
                ? $"{view.Count} {(view.Count == 1 ? "opportunity" : "opportunities")}"
                : $"{view.Count} of {_all.Count}";

            if (view.Count > 0)
            {
                state.Visible = false;
                dgv.Visible = true;
                dgv.ClearSelection();
            }
            else
            {
                dgv.Visible = false;

                if (_all.Count == 0)
                    state.Show("\uE73E", "No retention actions needed",
                        "No customer currently meets a retention trigger. Create loyalty programs or complete more repairs to generate opportunities.");
                else
                    state.Show("\uE721", "No matches",
                        $"Nothing matches \u201c{term}\u201d. Try a shorter word or a different category.");
            }
        }

        // ═══════════ GRID ═══════════
        private static void StyleGrid(DataGridView g)
        {
            g.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            g.BackgroundColor = UiKit.T.Surface;
            g.BorderStyle = BorderStyle.None;
            g.CellBorderStyle = DataGridViewCellBorderStyle.None;
            g.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
            g.EnableHeadersVisualStyles = false;
            g.GridColor = UiKit.T.LineSoft;

            g.RowHeadersVisible = false;
            g.AllowUserToAddRows = false;
            g.AllowUserToDeleteRows = false;
            g.AllowUserToResizeRows = false;
            g.AllowUserToOrderColumns = false;
            g.ReadOnly = true;
            g.MultiSelect = false;
            g.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            g.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.None;
            g.ScrollBars = ScrollBars.Vertical;
            g.RowTemplate.Height = UiKit.T.RowHeight;
            g.ColumnHeadersHeight = UiKit.T.HeaderHeight;
            g.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;

            g.ColumnHeadersDefaultCellStyle.BackColor = UiKit.T.Surface;
            g.ColumnHeadersDefaultCellStyle.ForeColor = UiKit.T.InkMuted;
            g.ColumnHeadersDefaultCellStyle.SelectionBackColor = UiKit.T.Surface;
            g.ColumnHeadersDefaultCellStyle.SelectionForeColor = UiKit.T.InkMuted;
            g.ColumnHeadersDefaultCellStyle.Font = UiKit.T.SmallStrong;
            g.ColumnHeadersDefaultCellStyle.Padding = new Padding(UiKit.T.S3, 0, UiKit.T.S3, 0);

            g.DefaultCellStyle.BackColor = UiKit.T.Surface;
            g.DefaultCellStyle.ForeColor = UiKit.T.Ink;
            g.DefaultCellStyle.Font = UiKit.T.Body;
            g.DefaultCellStyle.SelectionBackColor = UiKit.Wash(AppTheme.Primary);
            g.DefaultCellStyle.SelectionForeColor = UiKit.T.Ink;
            g.DefaultCellStyle.Padding = new Padding(UiKit.T.S3, 0, UiKit.T.S3, 0);
            g.DefaultCellStyle.WrapMode = DataGridViewTriState.False;
            g.RowsDefaultCellStyle.BackColor = UiKit.T.Surface;
        }

        private void ConfigureColumns()
        {
            foreach (var hidden in new[]
            {
                "CustomerId", "Email", "Phone", "LoyaltyProgramId",
                "TransactionCount", "Points",
                "CategoryDisplay", "LastVisitDisplay", "SpentDisplay"
            })
            {
                if (dgv.Columns[hidden] != null)
                    dgv.Columns[hidden].Visible = false;
            }

            void Setup(string name, string header, int width, int displayIndex, bool fill = false)
            {
                var c = dgv.Columns[name];
                if (c == null) return;

                c.HeaderText = header;
                c.SortMode = DataGridViewColumnSortMode.Automatic;
                c.AutoSizeMode = fill
                    ? DataGridViewAutoSizeColumnMode.Fill
                    : DataGridViewAutoSizeColumnMode.None;
                if (!fill) c.Width = width;
                else c.MinimumWidth = 200;
                c.DisplayIndex = displayIndex;
            }

            Setup("CustomerName", "Customer", 170, 0);
            Setup("Category", "Type", 120, 1);
            Setup("Action", "Recommended action", 190, 2);
            Setup("Basis", "Basis (why this customer)", 0, 3, fill: true);
            Setup("Reward", "Reward", 180, 4);
            Setup("TotalSpent", "Total spent", 100, 5);
            Setup("DaysSinceLastTransaction", "Last visit", 95, 6);

            if (dgv.Columns["CustomerName"] != null)
                dgv.Columns["CustomerName"].DefaultCellStyle.Font = UiKit.T.BodyStrong;

            if (dgv.Columns["Basis"] != null)
                dgv.Columns["Basis"].DefaultCellStyle.ForeColor = UiKit.T.InkMuted;

            if (dgv.Columns["TotalSpent"] != null)
                dgv.Columns["TotalSpent"].DefaultCellStyle.Format = "N2";
        }

        // ═══════════ ACTIONS MENU ═══════════
        private void BuildActionsMenu()
        {
            _actionsMenu = new ContextMenuStrip
            {
                Font = UiKit.T.Body,
                ShowImageMargin = false,
                BackColor = UiKit.T.Surface,
                ForeColor = UiKit.T.Ink,
                Renderer = new QuietMenuRenderer()
            };

            _actionsMenu.Items.Add("Log outreach…");
            _actionsMenu.Items.Add("View basis details");

            foreach (ToolStripItem item in _actionsMenu.Items)
                item.Padding = new Padding(UiKit.T.S2, UiKit.T.S1, UiKit.T.S2, UiKit.T.S1);

            _actionsMenu.Items[0].Click += (s, e) => LogOutreachForMenuRow();
            _actionsMenu.Items[1].Click += (s, e) => ShowBasisForMenuRow();

            _actionsMenu.Closed += (s, e) => { dgv.Invalidate(); };
        }

        private void AddActionsColumn()
        {
            if (dgv.Columns[ColActions] != null)
                dgv.Columns.Remove(ColActions);

            var col = new DataGridViewTextBoxColumn
            {
                Name = ColActions,
                HeaderText = "",
                Width = 44,
                AutoSizeMode = DataGridViewAutoSizeColumnMode.None,
                SortMode = DataGridViewColumnSortMode.NotSortable,
                Resizable = DataGridViewTriState.False,
                ReadOnly = true
            };

            dgv.Columns.Add(col);
            col.DisplayIndex = dgv.Columns.Count - 1;
        }

        // ═══════════ OUTREACH ACTIONS ═══════════
        private void LogOutreachForSelected()
        {
            if (dgv.CurrentRow == null)
            {
                MessageBox.Show("Select a customer first.",
                    "No selection", MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }

            if (dgv.CurrentRow.DataBoundItem is not RetentionRecommendationDto dto) return;
            OpenDialogFor(dto);
        }

        private void LogOutreachForMenuRow()
        {
            if (_menuRowIndex < 0) return;
            if (dgv.Rows[_menuRowIndex].DataBoundItem is not RetentionRecommendationDto dto) return;
            OpenDialogFor(dto);
        }

        private void ShowBasisForMenuRow()
        {
            if (_menuRowIndex < 0) return;
            if (dgv.Rows[_menuRowIndex].DataBoundItem is not RetentionRecommendationDto dto) return;
            ShowBasis(dto);
        }

        /// <summary>Shows the full measurable basis behind a recommendation.</summary>
        private void ShowBasis(RetentionRecommendationDto dto)
        {
            MessageBox.Show(
                $"Customer      {dto.CustomerName}\n" +
                $"Action        {dto.Action}\n\n" +
                $"WHY (basis)\n" +
                $"──────────────────────────────\n" +
                $"  • {dto.Basis}\n\n" +
                $"Measured customer history\n" +
                $"──────────────────────────────\n" +
                $"  • Completed transactions   {dto.TransactionCount}\n" +
                $"  • Total spending           \u20b1{dto.TotalSpent:N2}\n" +
                $"  • Last transaction         {dto.DaysSinceLastTransaction} days ago\n" +
                $"  • Loyalty points           {dto.Points}" +
                (string.IsNullOrWhiteSpace(dto.ProgramName) ? "" : $"\n  • Program                  {dto.ProgramName}"),
                "Basis for this recommendation",
                MessageBoxButtons.OK,
                MessageBoxIcon.Information);
        }

        private void OpenDialogFor(RetentionRecommendationDto dto)
        {
            using var dlg = new RetentionContactDialog(dto.CustomerId, dto.CustomerName,
                dto.CategoryDisplay, dto.Basis);
            if (dlg.ShowModal(this.FindForm()) == DialogResult.OK)
                _ = ReloadAsync();
        }

        // ═══════════ GRID EVENTS ═══════════
        private void Dgv_CellClick(object? sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0 || e.ColumnIndex < 0) return;
            if (dgv.Columns[e.ColumnIndex].Name != ColActions) return;

            _menuRowIndex = e.RowIndex;
            var cellRect = dgv.GetCellDisplayRectangle(e.ColumnIndex, e.RowIndex, true);
            _actionsMenu.Show(dgv, new Point(cellRect.Right - 200, cellRect.Bottom));
        }

        private void Dgv_CellDoubleClick(object? sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0) return;
            if (dgv.Rows[e.RowIndex].DataBoundItem is not RetentionRecommendationDto dto) return;
            ShowBasis(dto);
        }

        private void Dgv_CellMouseEnter(object? sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0) { _hoverRow = -1; return; }
            _hoverRow = e.RowIndex;
            dgv.Cursor = e.ColumnIndex >= 0 && dgv.Columns[e.ColumnIndex].Name == ColActions
                ? Cursors.Hand
                : Cursors.Default;
            dgv.InvalidateRow(e.RowIndex);
        }

        private void Dgv_CellMouseLeave(object? sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0) return;
            _hoverRow = -1;
            dgv.InvalidateRow(e.RowIndex);
        }

        // ═══════════ CELL PAINTING ═══════════
        private void Dgv_CellPainting(object? sender, DataGridViewCellPaintingEventArgs e)
        {
            if (e.Graphics == null) return;

            var g = e.Graphics;

            if (e.RowIndex == -1)
            {
                e.PaintBackground(e.CellBounds, false);
                e.PaintContent(e.CellBounds);
                using var hp = new Pen(UiKit.T.Line, 1);
                g.DrawLine(hp, e.CellBounds.Left, e.CellBounds.Bottom - 1,
                               e.CellBounds.Right, e.CellBounds.Bottom - 1);
                e.Handled = true;
                return;
            }

            if (e.RowIndex < 0 || e.ColumnIndex < 0) return;

            string col = dgv.Columns[e.ColumnIndex].Name;
            bool selected = (e.State & DataGridViewElementStates.Selected) != 0;
            bool hovered = e.RowIndex == _hoverRow;

            Color bg = selected
                ? e.CellStyle!.SelectionBackColor
                : hovered ? UiKit.T.RowHover : UiKit.T.Surface;

            bool custom = col == ColActions || col == "Category";

            using (var b = new SolidBrush(bg))
                g.FillRectangle(b, e.CellBounds);
            using (var p = new Pen(UiKit.T.LineSoft, 1))
                g.DrawLine(p, e.CellBounds.Left, e.CellBounds.Bottom - 1,
                              e.CellBounds.Right, e.CellBounds.Bottom - 1);

            if (!custom)
            {
                e.PaintContent(e.CellBounds);
                e.Handled = true;
                return;
            }

            UiKit.Quality(g);
            var r = e.CellBounds;

            if (col == ColActions)
            {
                var color = hovered ? UiKit.T.InkMuted : UiKit.T.InkFaint;
                UiKit.Text(g, "\u22EF", new Font("Segoe UI", 13F, FontStyle.Bold), color, r,
                    TextFormatFlags.HorizontalCenter | TextFormatFlags.VerticalCenter);
                e.Handled = true;
                return;
            }

            // Category pill
            if (col == "Category" && e.RowIndex < dgv.Rows.Count &&
                dgv.Rows[e.RowIndex].DataBoundItem is RetentionRecommendationDto rec)
            {
                var (color, label) = rec.Category switch
                {
                    "Reward" => (AppTheme.Success, "REWARD"),
                    "Discount" => (AppTheme.Warning, "DISCOUNT"),
                    "Follow-up" => (AppTheme.Primary, "FOLLOW-UP"),
                    "Re-engagement" => (AppTheme.Danger, "WIN-BACK"),
                    _ => (UiKit.T.InkMuted, rec.Category)
                };

                var pill = new Rectangle(r.X + UiKit.T.S2, r.Y + (r.Height - 22) / 2,
                    Math.Max(84, UiKit.Measure(label, UiKit.Micro).Width + 20), 22);

                UiKit.FillRounded(g, pill, 9, UiKit.Wash(color));
                UiKit.Text(g, label, UiKit.Micro, color, pill, UiKit.Center);
                e.Handled = true;
            }
        }

        // ═══════════ NESTED UI ═══════════

        [DesignerCategory("Code")]
        private sealed class SurfaceCard : Panel
        {
            public SurfaceCard()
            {
                SetStyle(ControlStyles.AllPaintingInWmPaint | ControlStyles.OptimizedDoubleBuffer
                       | ControlStyles.UserPaint | ControlStyles.ResizeRedraw, true);
                BackColor = AppTheme.Background;
            }

            protected override void OnPaint(PaintEventArgs e)
            {
                UiKit.Quality(e.Graphics);
                using (var b = new SolidBrush(AppTheme.Background))
                    e.Graphics.FillRectangle(b, ClientRectangle);
                UiKit.Card(e.Graphics, ClientRectangle, UiKit.T.Radius, UiKit.T.Surface, UiKit.T.Line);
                base.OnPaint(e);
            }
        }

        [DesignerCategory("Code")]
        private sealed class TabButton : Control
        {
            public string Category { get; }
            private readonly string _label;
            private bool _active, _hover;

            public TabButton(string label, string category)
            {
                _label = label;
                Category = category;
                SetStyle(ControlStyles.AllPaintingInWmPaint | ControlStyles.OptimizedDoubleBuffer
                       | ControlStyles.UserPaint | ControlStyles.ResizeRedraw, true);
                BackColor = AppTheme.Background;
                Cursor = Cursors.Hand;
                Font = UiKit.T.SmallStrong;
            }

            public int GetPreferredWidth() => UiKit.Measure(_label, UiKit.T.SmallStrong).Width + 32;

            [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
            [Browsable(false)]
            public bool IsActive
            {
                get => _active;
                set { _active = value; Invalidate(); }
            }

            protected override void OnMouseEnter(EventArgs e) { _hover = true; Invalidate(); base.OnMouseEnter(e); }
            protected override void OnMouseLeave(EventArgs e) { _hover = false; Invalidate(); base.OnMouseLeave(e); }

            protected override void OnPaint(PaintEventArgs e)
            {
                var g = e.Graphics;
                UiKit.Quality(g);

                using (var b = new SolidBrush(AppTheme.Background))
                    g.FillRectangle(b, ClientRectangle);

                if (_active)
                {
                    UiKit.FillRounded(g, ClientRectangle, 8, AppTheme.Primary);
                    UiKit.Text(g, _label, UiKit.T.SmallStrong, Color.White, ClientRectangle, UiKit.Center);
                }
                else
                {
                    if (_hover)
                        UiKit.FillRounded(g, ClientRectangle, 8, UiKit.T.RowHover);
                    UiKit.Text(g, _label, UiKit.T.SmallStrong, UiKit.T.InkMuted, ClientRectangle, UiKit.Center);
                }
            }
        }

        [DesignerCategory("Code")]
        private sealed class SearchBox : Control
        {
            public TextBox Inner { get; }
            private bool _focused;

            [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
            [Browsable(false)]
            public string PlaceholderText
            {
                get => Inner.PlaceholderText;
                set => Inner.PlaceholderText = value;
            }

            public SearchBox()
            {
                SetStyle(ControlStyles.AllPaintingInWmPaint | ControlStyles.OptimizedDoubleBuffer
                       | ControlStyles.UserPaint | ControlStyles.ResizeRedraw, true);
                BackColor = UiKit.T.Surface;

                Inner = new TextBox
                {
                    BorderStyle = BorderStyle.None,
                    Font = UiKit.T.Body,
                    ForeColor = UiKit.T.Ink,
                    BackColor = UiKit.T.Surface
                };
                Inner.GotFocus += (s, e) => { _focused = true; Invalidate(); };
                Inner.LostFocus += (s, e) => { _focused = false; Invalidate(); };

                Controls.Add(Inner);
            }

            protected override void OnResize(EventArgs e)
            {
                base.OnResize(e);
                Inner.Location = new Point(34, (Height - Inner.PreferredHeight) / 2);
                Inner.Width = Width - 46;
            }

            protected override void OnPaint(PaintEventArgs e)
            {
                var g = e.Graphics;
                UiKit.Quality(g);

                using (var b = new SolidBrush(UiKit.T.Surface))
                    g.FillRectangle(b, ClientRectangle);

                UiKit.FillRounded(g, new Rectangle(0, 0, Width, Height), 8, UiKit.T.Surface);

                var border = _focused ? AppTheme.Primary : UiKit.T.Line;
                using (var path = UiKit.Rounded(new Rectangle(0, 0, Width - 1, Height - 1), 8))
                using (var pen = new Pen(border, _focused ? 1.4f : 1f))
                    g.DrawPath(pen, path);

                UiKit.Text(g, "\uE721", UiKit.T.Glyph, _focused ? AppTheme.Primary : UiKit.T.InkFaint,
                    new Rectangle(10, 0, 20, Height),
                    TextFormatFlags.Left | TextFormatFlags.VerticalCenter);
            }
        }

        [DesignerCategory("Code")]
        private sealed class FlatButton : Control
        {
            private readonly string _glyph;
            private bool _hover, _down;

            public FlatButton(string text, string glyph)
            {
                _glyph = glyph;
                Text = text;
                SetStyle(ControlStyles.AllPaintingInWmPaint | ControlStyles.OptimizedDoubleBuffer
                       | ControlStyles.UserPaint | ControlStyles.ResizeRedraw, true);
                BackColor = AppTheme.Background;
                Cursor = Cursors.Hand;
                Font = UiKit.T.BodyStrong;
                TabStop = true;
            }

            public int PreferredWidth => UiKit.Measure(Text, UiKit.T.BodyStrong).Width + 56;

            protected override void OnMouseEnter(EventArgs e) { _hover = true; Invalidate(); base.OnMouseEnter(e); }
            protected override void OnMouseLeave(EventArgs e) { _hover = _down = false; Invalidate(); base.OnMouseLeave(e); }
            protected override void OnMouseDown(MouseEventArgs e) { _down = true; Invalidate(); base.OnMouseDown(e); }
            protected override void OnMouseUp(MouseEventArgs e) { _down = false; Invalidate(); base.OnMouseUp(e); }

            protected override void OnKeyDown(KeyEventArgs e)
            {
                if (e.KeyCode is Keys.Enter or Keys.Space)
                    InvokeOnClick(this, EventArgs.Empty);
                base.OnKeyDown(e);
            }

            protected override void OnPaint(PaintEventArgs e)
            {
                var g = e.Graphics;
                UiKit.Quality(g);

                using (var b = new SolidBrush(AppTheme.Background))
                    g.FillRectangle(b, ClientRectangle);

                Color bg = _down ? AppTheme.PrimaryActive
                         : _hover ? AppTheme.PrimaryHover
                         : AppTheme.Primary;

                UiKit.FillRounded(g, ClientRectangle, 8, bg);

                UiKit.Text(g, _glyph, new Font("Segoe MDL2 Assets", 10F), Color.White,
                    new Rectangle(16, 0, 18, Height),
                    TextFormatFlags.Left | TextFormatFlags.VerticalCenter);

                UiKit.Text(g, Text, UiKit.T.BodyStrong, Color.White,
                    new Rectangle(36, 0, Width - 46, Height),
                    TextFormatFlags.Left | TextFormatFlags.VerticalCenter);
            }
        }

        [DesignerCategory("Code")]
        private sealed class StateView : Control
        {
            private string _glyph = "";
            private string _title = "";
            private string _message = "";

            public StateView()
            {
                SetStyle(ControlStyles.AllPaintingInWmPaint | ControlStyles.OptimizedDoubleBuffer
                       | ControlStyles.UserPaint | ControlStyles.ResizeRedraw, true);
                BackColor = UiKit.T.Surface;
            }

            public void Show(string glyph, string title, string message)
            {
                _glyph = glyph; _title = title; _message = message;
                Visible = true;
                BringToFront();
                Invalidate();
            }

            protected override void OnPaint(PaintEventArgs e)
            {
                var g = e.Graphics;
                UiKit.Quality(g);

                using (var b = new SolidBrush(UiKit.T.Surface))
                    g.FillRectangle(b, ClientRectangle);

                int cy = Height / 2 - 40;

                var circle = new Rectangle(Width / 2 - 26, cy, 52, 52);
                UiKit.FillRounded(g, circle, 26, UiKit.T.LineSoft);
                UiKit.Text(g, _glyph, UiKit.T.GlyphLarge, UiKit.T.InkFaint, circle,
                    TextFormatFlags.HorizontalCenter | TextFormatFlags.VerticalCenter);

                UiKit.Text(g, _title, UiKit.T.Section, UiKit.T.Ink,
                    new Rectangle(0, circle.Bottom + UiKit.T.S4, Width, 24),
                    TextFormatFlags.HorizontalCenter | TextFormatFlags.Top);

                int msgW = Math.Min(420, Width - UiKit.T.S6 * 2);
                UiKit.Text(g, _message, UiKit.T.Body, UiKit.T.InkMuted,
                    new Rectangle((Width - msgW) / 2, circle.Bottom + UiKit.T.S4 + 28, msgW, 60),
                    TextFormatFlags.HorizontalCenter | TextFormatFlags.Top | TextFormatFlags.WordBreak);
            }
        }

        private sealed class QuietMenuRenderer : ToolStripProfessionalRenderer
        {
            public QuietMenuRenderer() : base(new Colors()) { RoundedEdges = false; }

            protected override void OnRenderMenuItemBackground(ToolStripItemRenderEventArgs e)
            {
                var r = new Rectangle(4, 0, e.Item.Width - 8, e.Item.Height);
                if (e.Item.Selected)
                    UiKit.FillRounded(e.Graphics, r, 6, UiKit.T.RowHover);
            }

            protected override void OnRenderSeparator(ToolStripSeparatorRenderEventArgs e)
            {
                using var pen = new Pen(UiKit.T.LineSoft, 1);
                int y = e.Item.Height / 2;
                e.Graphics.DrawLine(pen, 8, y, e.Item.Width - 8, y);
            }

            private sealed class Colors : ProfessionalColorTable
            {
                public override Color ToolStripDropDownBackground => UiKit.T.Surface;
                public override Color MenuBorder => UiKit.T.Line;
                public override Color MenuItemBorder => Color.Transparent;
                public override Color ImageMarginGradientBegin => UiKit.T.Surface;
                public override Color ImageMarginGradientMiddle => UiKit.T.Surface;
                public override Color ImageMarginGradientEnd => UiKit.T.Surface;
            }
        }
    }
}
